name: Setup
description: Setup Env

runs:
  using: composite
  steps:
    - name: Upload All APK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ikun-music-mobile-apks
        path: |
          android/app/build/outputs/apk/release/*.apk
          android/app/build/outputs/apk/debug/*.apk
        if-no-files-found: error
